# Generated by Django 4.2.16 on 2024-09-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='address',
            field=models.TextField(default='Not available', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='housing_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('castle', 'Castle'), ('villa', 'Villa'), ('camping', 'Camping')], default='not available', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='room_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
